config/routes.rb
Meccademia::Application.routes.draw do
  resources :users

  resources :fine_collections

  resources :students

  root 'users#homepage'
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/fine_collection.rb
class FineCollection < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  @books= Book.all
  end

  def new
    @book = Book.new
  end


  def show

  end

  def create
  @book=Book.new(book_params)
  @book.save
    redirect_to  books_path
  end

  def update

  end

  def edit

  end

  private
  def book_params
    params.require(:book).permit(:name,:author,:isbn,:quantity)
  end

end

app/controllers/fine_collections_controller.rb
class FineCollectionsController < ApplicationController
  before_action :set_fine_collection, only: [:show, :edit, :update, :destroy]

  # GET /fine_collections
  # GET /fine_collections.json
  def index
    @fine_collections = FineCollection.all
  end

  # GET /fine_collections/1
  # GET /fine_collections/1.json
  def show
  end

  # GET /fine_collections/new
  def new
    @fine_collection = FineCollection.new
  end

  # GET /fine_collections/1/edit
  def edit
  end

  # POST /fine_collections
  # POST /fine_collections.json
  def create
    @fine_collection = FineCollection.new(fine_collection_params)

    respond_to do |format|
      if @fine_collection.save
        format.html { redirect_to @fine_collection, notice: 'Fine collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fine_collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @fine_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fine_collections/1
  # PATCH/PUT /fine_collections/1.json
  def update
    respond_to do |format|
      if @fine_collection.update(fine_collection_params)
        format.html { redirect_to @fine_collection, notice: 'Fine collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fine_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fine_collections/1
  # DELETE /fine_collections/1.json
  def destroy
    @fine_collection.destroy
    respond_to do |format|
      format.html { redirect_to fine_collections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine_collection
      @fine_collection = FineCollection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_collection_params
      params.require(:fine_collection).permit(:fine_amount, :due_date, :return_date)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email_address, :phone_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :mobile_number, :email, :encrypted_password, :user_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/fine_collections_helper.rb
module FineCollectionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%=form_for @book,url:{action:"create"} do |f| %>
    <%=f.text_field :name%>
    <%=f.text_field :author%>
    <%=f.text_field :isbn%>
    <%=f.text_field :quantity%>
    <%=f.submit "create"%>
<%end%>

app/views/books/index.html.erb
<h3>Books</h3>

<%= @books.name %>

<%=link_to new_book_path do %>
Add book
<%end%>

app/views/books/new.html.erb
<legend> Add Book </legend>
<%= render 'form'%>

app/views/fine_collections/_form.html.erb
<%= form_for(@fine_collection) do |f| %>
  <% if @fine_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fine_collection.errors.count, "error") %> prohibited this fine_collection from being saved:</h2>

      <ul>
      <% @fine_collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fine_amount %><br>
    <%= f.text_field :fine_amount %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :return_date %><br>
    <%= f.datetime_select :return_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fine_collections/edit.html.erb
<h1>Editing fine_collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @fine_collection %> |
<%= link_to 'Back', fine_collections_path %>

app/views/fine_collections/index.html.erb
<h1>Listing fine_collections</h1>

<table>
  <thead>
    <tr>
      <th>Fine amount</th>
      <th>Due date</th>
      <th>Return date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fine_collections.each do |fine_collection| %>
      <tr>
        <td><%= fine_collection.fine_amount %></td>
        <td><%= fine_collection.due_date %></td>
        <td><%= fine_collection.return_date %></td>
        <td><%= link_to 'Show', fine_collection %></td>
        <td><%= link_to 'Edit', edit_fine_collection_path(fine_collection) %></td>
        <td><%= link_to 'Destroy', fine_collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fine collection', new_fine_collection_path %>

app/views/fine_collections/new.html.erb
<h1>New fine_collection</h1>

<%= render 'form' %>

<%= link_to 'Back', fine_collections_path %>

app/views/fine_collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fine amount:</strong>
  <%= @fine_collection.fine_amount %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @fine_collection.due_date %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @fine_collection.return_date %>
</p>

<%= link_to 'Edit', edit_fine_collection_path(@fine_collection) %> |
<%= link_to 'Back', fine_collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meccademia</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="../assets/js/html5shiv.js"></script>
  <![endif]-->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style type="text/css"></style>
  <style id="holderjs-style" type="text/css">.holderjs-fluid {
      font-size: 16px;
      font-weight: bold;
      text-align: center;
      font-family: sans-serif;
      margin: 0
  }</style>

</head>

<body>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

 <!-- NAVBAR
  ================================================== -->
  <div class="navbar-wrapper">
    <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
    <div class="container">

      <%= render 'shared/header' %>
    </div>
    <!-- /.container -->
  </div>
  <!-- /.navbar-wrapper -->

  <%= yield %>



  <!-- /END THE FEATURETTES -->

<%=render 'shared/footer'%>
<!-- /.container -->

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>FOOTER</p>
</footer>

app/views/shared/_header.html.erb
<div>
  <div style="float: left;margin-left:0px; margin-bottom: 15px;">
    <%= link_to(image_tag("meccademia_logo.jpeg"), root_path, :class => "logo") %>
  </div>

  <div style="float: right; width: 90%;">

    <div style="text-align: right; padding-top: 10px; padding-bottom: 10px;">
      Welcome
     <span>

              <%#= link_to "Register", new_registration_path(:user) %>
           <%#= link_to("Login", sign_in_path) %>
          <%# else %>
           <%# if current_user.role?('admin') || current_user.role?('program-volunteer') %>
                <%#= link_to "Admin", admin_schools_path %>
           <%# end %>
           <%#= link_to("Logout", destroy_user_session_path, :method => :delete) %>
          <%# end %>
     </span>
    </div>

    <div class="navbar navbar-default">
    <div class="navbar-brand"><span>Meccademia Library</span></div>


      <div class="navbar-inner">
        <%=render 'shared/navbar'%>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input class="form-control" style="width: 120px" placeholder="Search" type="text">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="javascript:void(0)">Action</a></li>
              <li><a href="javascript:void(0)">Another action</a></li>
              <li><a href="javascript:void(0)">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="javascript:void(0)">Separated link</a></li>
            </ul>
          </li>
        </ul>
        <div class="nav-collapse collapse">
          <%#= render "shared/navbar" %>
        </div>
        <!--/.nav-collapse -->
      </div>
      <!-- /.navbar-inner -->

    </div>
    <!-- /.navbar -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div data-no-turbolink>
  <ul class="nav navbar-nav">


    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="javascript:void(0)">Action</a></li>
        <li><a href="javascript:void(0)">Another action</a></li>
        <li><a href="javascript:void(0)">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="javascript:void(0)">Separated link</a></li>
    </ul>
    </li>

      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="javascript:void(0)">Action</a></li>
          <li><a href="javascript:void(0)">Another action</a></li>
          <li><a href="javascript:void(0)">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="javascript:void(0)">Separated link</a></li>
         </ul>
    </li>


    <li class="dropdown">
      <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="javascript:void(0)">Action</a></li>
        <li><a href="javascript:void(0)">Another action</a></li>
        <li><a href="javascript:void(0)">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="javascript:void(0)">Separated link</a></li>
      </ul>

    </li>
  </ul>

</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th>Phone number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email_address %></td>
        <td><%= student.phone_number %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @student.email_address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @student.phone_number %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :mobile_number %><br>
    <%= f.number_field :mobile_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :encrypted_password %><br>
    <%= f.text_field :encrypted_password %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Mobile number</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>User name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.mobile_number %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.user_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @user.mobile_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>